default_stages: [pre-commit, pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.15
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.11
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: ty
        name: Run ty type checker
        entry: uv run ty check
        language: system
        types: [python]
        # Set pass_filenames: true to run the hook only on staged files
        pass_filenames: true
